const characters={
 liang:{name:'梁志成',profile:'52岁，大陆维修师傅。固执、务实、不说漂亮话，重视安全和记录；会承认错误，也提醒年轻人表达问题时给人留余地。'},
 xu:{name:'许澄',profile:'34岁，大陆研发负责人。“换手”机器人项目负责人。专注直接，支持技术进步，也承认技术部署中的工人权益和流程责任。'},
 zhou:{name:'周野',profile:'27岁，周予安的弟弟，台湾青年，现场操作员。较早融入团队，秘密参与“换手”项目并希望争取工人收益。'},
 he:{name:'何柏翰',profile:'31岁，周予安的台湾朋友，在榕海做测试工作。经历过真实挫折，仍计划另寻发展，对统一和去留保留复杂看法。'}
};
const json=(value,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
const clean=(value,max)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw Error('Invalid text');return value.trim()};
export function validateDialogue(input){if(!input||!characters[input.npc])throw Error('Invalid NPC');const message=clean(input.message,160);if(!Number.isInteger(input.quest)||input.quest<0||input.quest>4)throw Error('Invalid quest');if(!Array.isArray(input.met)||input.met.length>4||input.met.some(id=>!characters[id]))throw Error('Invalid meetings');if(!Array.isArray(input.memories)||input.memories.length>4)throw Error('Invalid memories');return{npc:input.npc,message,quest:input.quest,met:[...new Set(input.met)],memories:input.memories.map(m=>clean(m,600))}}
export function validateReply(data){return clean(data?.reply,280)}
async function readBody(request){if(Number(request.headers.get('content-length'))>12000)throw Error('Too large');const reader=request.body?.getReader();if(!reader)throw Error('Missing body');let size=0,body='';const decoder=new TextDecoder();while(true){const{done,value}=await reader.read();if(done)break;size+=value.length;if(size>12000){await reader.cancel();throw Error('Too large')}body+=decoder.decode(value,{stream:true})}return body+decoder.decode()}
export async function handleApi(request,env,fetcher=fetch){const path=new URL(request.url).pathname;if(path==='/api/status'&&request.method==='GET')return json({configured:!!env.DEEPSEEK_API_KEY,model:'deepseek-flash'});if(path!=='/api/dialogue')return json({error:'Not found'},404);if(request.method!=='POST')return json({error:'Method not allowed'},405);if(!request.headers.get('content-type')?.startsWith('application/json')||request.headers.get('sec-fetch-site')==='cross-site')return json({error:'Invalid request'},403);if(!env.DEEPSEEK_API_KEY)return json({error:'DeepSeek 尚未配置，当前可使用本地剧情对话。'},503);let turn;try{turn=validateDialogue(JSON.parse(await readBody(request)))}catch{return json({error:'Invalid dialogue state'},400)}
 const npc=characters[turn.npc],questText=['周予安刚入职，需找老梁确认检查安排','周予安指出试验表疑点，正调查控制柜','周予安发现过温警告没有复核签名','异常已记录，周予安在认识同事','序章第一天结束'][turn.quest];
 try{const response=await fetcher('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${env.DEEPSEEK_API_KEY}`},signal:AbortSignal.timeout(40000),body:JSON.stringify({model:'deepseek-flash',thinking:{type:'disabled'},max_tokens:320,response_format:{type:'json_object'},messages:[{role:'system',content:`你在现实主义2D RPG《最后一班》中扮演${npc.name}。${npc.profile}\n背景固定：2040年统一后的福建榕海，和盛智造是大陆自主研发制造企业；主角周予安是32岁台湾青年，因AI失业来大陆谋生，起初保持距离。人物不能预知未来火灾，不得改变固定事实，不要说教，不要替玩家下结论。你只知道亲历和已知信息。回应应像现场口语，有个性、克制、具体，可不同意玩家。只输出JSON：{"reply":"不超过140个中文字的一段回应"}。不要输出其他字段。`},{role:'user',content:JSON.stringify({scene:questText,playerSays:turn.message,peopleMet:turn.met,sharedMemories:turn.memories})}]})});if(!response.ok){const messages={401:'DeepSeek API Key 无效。',402:'DeepSeek 账户余额不足。',429:'DeepSeek 请求过于频繁，请稍后再试。'};return json({error:messages[response.status]||'DeepSeek 暂时无法回应。'},502)}const data=await response.json();if(data.choices?.[0]?.finish_reason!=='stop')throw Error('Incomplete');return json({reply:validateReply(JSON.parse(data.choices[0].message.content)),model:'deepseek-flash'})}catch{return json({error:'NPC 没有及时形成有效回应，请再试一次。'},502)}}
